# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ccr8m8cm6-capi-aws
  namespace: ccr8m8cm6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ccr8m8cm6-capi-aws
subjects:
- kind: ServiceAccount
  name: ccr8m8cm6-capi-aws
